import type { Metadata } from "next";
import App from "./app";
import "./globals.css";
import SessionApp from "./sessionApp";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`antialiased`}
      >
        <SessionApp>
          <App>
            {children}  
          </App>
        </SessionApp>
      </body>
    </html>
  );
}
